[app]
backend_url = "https://evm.ioogle.io/api"

[[chains]]
id = 1
name = "ethereum"
alias = "Ethereum Mainnet"
block_explorer = "https://etherscan.io"
etherscan_api_token = ""
rpc = "https://eth-mainnet.g.alchemy.com/v2/"
