[app]
backend_url = "http://localhost:8080"

[[chains]]
id = 1
name = "ethereum"
alias = "Ethereum Mainnet"
block_explorer = "https://etherscan.io"
etherscan_api_token = ""
rpc = "https://eth-mainnet.g.alchemy.com/v2/"
